
const SHA256 = require('crypto-js/sha256')

class Block{

    constructor(index, timestamp, data, precedingHash="") {
        // tracks position of every block
        this.index = index
        // records time of each trnasaction
        this.timestamp = timestamp
        // data about the transaction
        this.data = data
        // hash of the preceding block so we can see if the blockchain is valid
        this.precedingHash = precedingHash
        // own hash that becomes generated by computeHash
        this.hash = this.computeHash();
    }


    // takes the whole input to create a hash
    computeHash() {
        return SHA256(this.index + this.precedingHash + this.timestamp + JSON.stringify(this.data)).toString()
    }

}


